version: '2'
services:
    seek-app:
        image: seek
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://seek-mysql:3306/seek?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8088:8088
    seek-mysql:
        extends:
            file: mysql.yml
            service: seek-mysql
